const express = require("express");
const adminBaixaParticipacaoRoutes = require("./admin-baixa-participacao.routes");
const adminDashboardRoutes = require("./admin-dashboard.routes");
const adminEnvioDesafioRoutes = require("./admin-envio-desafio.routes");
const adminPontuacaoRoutes = require("./admin-pontuacao.routes");
const adminRelatorioParticipacaoRoutes = require("./admin-relatorio-participacao.routes");
const auditoriaRoutes = require("./auditoria.routes");
const authRoutes = require("./auth.routes");
const configurationRoutes = require("./configuration.routes");
const desafioRoutes = require("./desafio.routes");
const envioDesafioRoutes = require("./envio-desafio.routes");
const grupoRoutes = require("./grupo.routes");
const healthRoutes = require("./health.routes");
const heuristicRoutes = require("./heuristic.routes");
const meDashboardRoutes = require("./me-dashboard.routes");
const mePontuacaoRoutes = require("./me-pontuacao.routes");
const pilarRoutes = require("./pilar.routes");
const profileRoutes = require("./profile.routes");
const rankingRoutes = require("./ranking.routes");
const studentRoutes = require("./student.routes");
const turmaRoutes = require("./turma.routes");
const usersRoutes = require("./users.routes");
const usuarioRoutes = require("./usuario.routes");

const router = express.Router();

router.use(adminBaixaParticipacaoRoutes);
router.use(adminDashboardRoutes);
router.use(adminEnvioDesafioRoutes);
router.use(adminPontuacaoRoutes);
router.use(adminRelatorioParticipacaoRoutes);
router.use(auditoriaRoutes);
router.use("/auth", authRoutes);
router.use("/configuracoes", configurationRoutes);
router.use(desafioRoutes);
router.use(envioDesafioRoutes);
router.use(grupoRoutes);
router.use("/heuristicas", heuristicRoutes);
router.use("/health", healthRoutes);
router.use(meDashboardRoutes);
router.use(mePontuacaoRoutes);
router.use(pilarRoutes);
router.use(profileRoutes);
router.use(rankingRoutes);
router.use(studentRoutes);
router.use(turmaRoutes);
router.use("/users", usersRoutes);
router.use("/usuarios", usuarioRoutes);

module.exports = router;
