export const domainPages = {
  registrarDesafio: {
    eyebrow: "Aluno",
    title: "Registrar desafio",
    summary: "Envios individuais ou em grupo ficam pendentes ate a avaliacao do professor.",
    highlights: [
      "Pilar do Metodo do Alavanque",
      "Desafio executado",
      "Participantes do grupo ate 5 alunos",
      "Descricao e evidencia obrigatoria",
    ],
  },
  meusDesafios: {
    eyebrow: "Aluno",
    title: "Meus desafios",
    summary: "Historico dos envios realizados pelo aluno com acompanhamento de status.",
    highlights: ["Pendente", "Aprovado", "Reprovado", "Ajuste solicitado"],
  },
  minhaPontuacao: {
    eyebrow: "Aluno",
    title: "Minha pontuacao",
    summary: "Resumo individual de pontos recebidos por desafios aprovados.",
    highlights: ["Pontos totais", "Pontuacao por pilar", "Historico de pontos", "Melhor pilar"],
  },
  meusGrupos: {
    eyebrow: "Aluno",
    title: "Meus grupos",
    summary: "Grupos relacionados aos desafios em que o aluno participa.",
    highlights: ["Responsavel pelo envio", "Participantes", "Status do envio", "Pontos apos aprovacao"],
  },
  ranking: {
    eyebrow: "Mentoria",
    title: "Ranking",
    summary: "Classificacao por pontos concedidos a partir dos desafios aprovados.",
    highlights: ["Geral", "Por turma", "Por pilar", "Por periodo"],
  },
  perfil: {
    eyebrow: "Aluno",
    title: "Meu perfil",
    summary: "Dados cadastrais do usuario autenticado e vinculos com a mentoria.",
    highlights: ["Nome", "E-mail", "Perfil", "Status"],
  },
  alunos: {
    eyebrow: "Admin",
    title: "Alunos",
    summary: "Gestao dos alunos cadastrados na mentoria.",
    highlights: ["Cadastro", "Status", "Turmas", "Participacao"],
  },
  turmas: {
    eyebrow: "Admin",
    title: "Turmas",
    summary: "Organizacao dos alunos por turma da mentoria.",
    highlights: ["Nome", "Data de inicio", "Data de fim", "Status"],
  },
  pilares: {
    eyebrow: "Admin",
    title: "Pilares",
    summary: "Topicos principais do Metodo do Alavanque usados nos desafios.",
    highlights: [
      "Conhecimento Tecnico Alinhado ao Mercado",
      "Posicionamento e Softskills",
      "Pratica",
      "Exposicao a Problemas",
      "Compartilhamento",
      "Networking",
      "Visibilidade",
    ],
  },
  desafios: {
    eyebrow: "Admin",
    title: "Desafios",
    summary: "Cadastro dos desafios disponiveis com pontuacao fixa.",
    highlights: ["Pilar", "Titulo", "Pontuacao", "Tipo individual ou grupo"],
  },
  aprovacoes: {
    eyebrow: "Admin",
    title: "Aprovacoes",
    summary: "Fila de envios pendentes de avaliacao pelo professor.",
    highlights: ["Aprovar", "Reprovar", "Solicitar ajuste", "Feedback"],
  },
  grupos: {
    eyebrow: "Admin",
    title: "Grupos",
    summary: "Consulta dos grupos formados nos envios de desafios.",
    highlights: ["Lider", "Participantes", "Turma", "Pontuacao"],
  },
  relatorios: {
    eyebrow: "Admin",
    title: "Relatorios",
    summary: "Indicadores de participacao e engajamento dos alunos.",
    highlights: ["Alunos ativos", "Envios pendentes", "Ranking por turma", "Baixa participacao"],
  },
  configuracoes: {
    eyebrow: "Admin",
    title: "Configuracoes",
    summary: "Parametros iniciais para manter a aplicacao alinhada ao MVP.",
    highlights: ["Perfis", "Status", "Menus", "Tema claro e escuro"],
  },
};
